In [2]:
import numpy as np

In [3]:
from tqdm import tqdm

In [4]:
from keras.datasets import fashion_mnist

2023-03-14 11:55:00.344786: I tensorflow/core/platform/cpu_feature_guard.cc:193] This TensorFlow binary is optimized with oneAPI Deep Neural Network Library (oneDNN) to use the following CPU instructions in performance-critical operations:  AVX2 AVX_VNNI FMA
To enable them in other operations, rebuild TensorFlow with the appropriate compiler flags.
2023-03-14 11:55:00.427720: I tensorflow/core/util/util.cc:169] oneDNN custom operations are on. You may see slightly different numerical results due to floating-point round-off errors from different computation orders. To turn them off, set the environment variable `TF_ENABLE_ONEDNN_OPTS=0`.
2023-03-14 11:55:00.446009: E tensorflow/stream_executor/cuda/cuda_blas.cc:2981] Unable to register cuBLAS factory: Attempting to register factory for plugin cuBLAS when one has already been registered
2023-03-14 11:55:00.699194: W tensorflow/stream_executor/platform/default/dso_loader.cc:64] Could not load dynamic library 'libnvinfer.so.7'; dlerror: li

In [5]:
(X_train, y_train), (X_test, y_test) = fashion_mnist.load_data()

In [6]:
X_train.shape

(60000, 28, 28)

In [7]:
y_train.shape

(60000,)

In [8]:
np.random.seed(42)

In [9]:
def one_hot(a):
    b = np.zeros((a.size, a.max() + 1))
    b[np.arange(a.size), a] = 1
    return b

In [10]:
one_hot(y_train)

array([[0., 0., 0., ..., 0., 0., 1.],
       [1., 0., 0., ..., 0., 0., 0.],
       [1., 0., 0., ..., 0., 0., 0.],
       ...,
       [0., 0., 0., ..., 0., 0., 0.],
       [1., 0., 0., ..., 0., 0., 0.],
       [0., 0., 0., ..., 0., 0., 0.]])

In [11]:
def Preprocess(X,y):
    '''Unrolls X,y, rehsapes into column vectors, one hots y'''
    X_processed=[]
    y_processed=[]
    
    for i in range(np.shape(X)[0]):
        X_processed.append(X_train[i].ravel())
    y_processed=one_hot(y_train.ravel()).T
    return np.array(X_processed).T,y_processed
        
    

In [12]:
X_train_clean,y_train_clean=Preprocess(X_train,y_train)

In [13]:
Xtest,ytest=Preprocess(X_test,y_test)

In [14]:
def tran_val_split(X,y,split=0.1):
    len_split=int(np.shape(X)[1]*split)
    np.random.shuffle(X)
    np.random.shuffle(y)
    X_val=X[:,:len_split]
    y_val=y[:,:len_split]
    
    X_train=X[:,len_split:]
    y_train=y[:,len_split:]
    
    return (X_train,y_train),(X_val,y_val)
    
        

In [15]:
(Xtrain,ytrain),(Xval,yval)=tran_val_split(X_train_clean,y_train_clean)

In [16]:
# def get_loss(loss='logloss'):
    

In [17]:

def sigmoid(x):
    return np.where(x >= 0, 
                    1 / (1 + np.exp(-x)), 
                    np.exp(x) / (1 + np.exp(x)))
def softmax(x):

    z=x-np.max(x,axis=0) #doing this for numerical stability, prevents over/undeflow
    return np.exp(z)/np.sum(np.exp(z),axis=0)

In [18]:
def get_activation(activation):#maybe getderivatives here iteself ?
    def sigmoid(x):
        return np.where(x >= 0, 
                        1 / (1 + np.exp(-x)), 
                        np.exp(x) / (1 + np.exp(x)))
    def softmax(x):
        z=x-np.max(x,axis=0)
        return np.exp(z)/np.sum(np.exp(z),axis=0)
    if activation=='sigmoid':
        return sigmoid
    elif activation=='softmax':
        return softmax
    elif activation== 'tanh':
        return np.tanh(x)

In [19]:
def get_activation_derivative(activation):#maybe getderivatives here iteself ?
    def sigmoid_d(x):
        sig= np.where(x >= 0, 1 / (1 + np.exp(-x)), np.exp(x) / (1 + np.exp(x)))
        sig=1/(1+np.exp(-x))
        return sig*(1-sig)
    def softmax_d(x):
        z=x-np.max(x,axis=0)
        soft=np.exp(z)/np.sum(np.exp(z),axis=0)
        return soft*(1-soft)
    if activation=='sigmoid':
        return sigmoid_d
    elif activation=='softmax':
        '''
        need to think more, not required for backprop as we look directly at dL/da_l
        But still, for the sake of completeness, and if user wants softmax in the middle?
        d S(x_i) /d x_j= S(x_i)*(kronecker delta_i,j -S(x_j))
        But we care about only dh_k,j/da_k,j So no need to implement d S(x_i) /d x_j
        d S(x_i) /d x_i should suffice
        so we get array of [ d S(x_1) /d x_1, d S(x_2) /d x_2, ....]
        '''
        
        return softmax_d
    elif activation=='tanh':
        return 1-tanh(x)**2

In [20]:
class layer:
    def __init__(self,input_size,output_size,activation='sigmoid'):
            
        ''' 
        output size number of neurons i
        input size j
        
        '''
        self.W=np.random.randn(output_size,input_size)*0.01 #size ixj
        self.b=np.random.randn(output_size,1)*0.01           #size i
        self.a=np.random.randn(output_size,1)*0.01           #size i
        self.h=np.random.randn(output_size,1)*0.01           #size i
        self.g=get_activation(activation)
        
        self.d_a=np.zeros((output_size,1))
        self.d_h=np.zeros((output_size,1))
        self.d_W=np.zeros((output_size,input_size))
        self.d_b=np.zeros((output_size,1))
        self.d_g=get_activation_derivative(activation)
        
        
        
    def forward(self, inputs):
        self.a=self.b+np.matmul(self.W,inputs)
        self.h=self.g(self.a)
        return self.h
    def reset(self):
        self.d_a=np.zeros(np.shape(self.d_a))
        self.d_h=np.zeros(np.shape(self.d_h))
        self.d_W=np.zeros(np.shape(self.d_W))
        self.d_b=np.zeros(np.shape(self.d_b))
        


In [21]:
temp=[1,2,3,4]
temp1=[1,2,3,4]

In [22]:
class Model:
    def __init__(self,X_size,Y_size,hidden_layer_sizes=[4],hidden_layer_activations=['sigmoid']):
        '''
        '''   
        
        self.input_size=X_size
        self.output_size=Y_size
        self.hidden_layer_sizes=hidden_layer_sizes
        self.layers=[]
        
        prev_size=self.input_size
    
        for size,activation in zip(hidden_layer_sizes,hidden_layer_activations):
            self.layers.append(layer(prev_size,size,activation))
            prev_size=size
        self.layers.append(layer(size,self.output_size,'softmax'))
        
    def forward(self,x):
        output=x
        # print(output.shape)
        for layer in  self.layers:
            # print('W',layer.W.shape)
            output=layer.forward(output)
            # print(output.shape)   
        return output
    
    def reset(self):
        for layer in  self.layers:
            # resets the dWs
            layer.reset()
        
    
          
            
    def backward(self,x,y,y_pred):
        # self.layers[-1].d_h is not needed as d_h is used to calculate d_a and self.layers[-1].h is softmax
        self.layers[-1].d_a=-(y-y_pred)
        
        
        for idx in range(len(self.layers)-1,0,-1): #goes from L->2, for l=1 we do outside
            
            
            #compute gradient wrt parameters
            self.layers[idx].d_W+=np.matmul(self.layers[idx].d_a,np.transpose(self.layers[idx-1].h))
            self.layers[idx].d_b+=self.layers[idx].d_a
            
            #compute gradient wrt layer below -- will help in next layer iter
            self.layers[idx-1].d_h=np.matmul(np.transpose(self.layers[idx].W),self.layers[idx].d_a)
            
            #compute gradient -- element wise multiplivation, derivative of the activation function of layer idx-1
            self.layers[idx-1].d_a=self.layers[idx-1].d_h*self.layers[idx-1].d_g(self.layers[idx-1].a)
                        
        self.layers[0].d_W+=np.matmul(self.layers[0].d_a,np.transpose(x))
        self.layers[0].d_b+=self.layers[0].d_a 
        
        
                    
                
                
            
            
            
        
    
            
            
        
            
            

In [23]:
class optimizers(Model):
    def __init__(self,X_size,Y_size,hidden_layer_sizes=[4],hidden_layer_activations=['sigmoid']):
        super().__init__(X_size,Y_size,hidden_layer_sizes,hidden_layer_activations)

    def batch_gradient_descent(self,X,Y,eta=1,batch_size=1,max_iters=1000):
        
        '''
        Mini-Batch Gradient Descent
        at batchsize=1, behaves like sgd, batchsize=np.shape(X), behaves as gd
        eta is the learning rate
        '''
        
        
        

        for t in tqdm(range(max_iters)):
            number_points_seen=0
            for i in range(np.shape(X)[1]):
                x=X[:,[i]]
                y=Y[:,[i]]
                y_pred=self.forward(x)
                self.backward(x,y,y_pred)
                number_points_seen+=1
                
                #update if the number of points seen==batch size, or if data ends
                if number_points_seen%batch_size==0 or number_points_seen==np.shape(X)[1]:
                    for layer in self.layers:
                        layer.W=layer.W-eta*layer.d_W
                        layer.b=layer.b-eta*layer.d_b
                    self.reset() #reset grads before new epoch
            
            
    def stochastic_gradient_descent(self,X,Y,eta=1,max_iters=1000):
        
        
        '''
        stochastic Gradient Descent
        '''
                
        

        for t in tqdm(range(max_iters)):
            for i in range(np.shape(X)[1]):
                x=X[:,[i]]
                y=Y[:,[i]]
                y_pred=self.forward(x)
                self.backward(x,y,y_pred)
                
                #update
                for layer in self.layers:
                    layer.W=layer.W-eta*layer.d_W
                    layer.b=layer.b-eta*layer.d_b
                self.reset() #reset grads before new update
                    
            
        
        
    def Momentum_based(self,X,Y,eta=1,beta=0.9,batch_size=100,max_iters=1000):
        ''''''
        u_W=[np.zeros(np.shape(layer.d_W)) for layer in self.layers]
        u_b=[np.zeros(np.shape(layer.d_b)) for layer in self.layers]

        



        for t in tqdm(range(max_iters)):
            number_points_seen=0
            for i in range(np.shape(X)[1]):
                x=X[:,[i]]
                y=Y[:,[i]]
                y_pred=self.forward(x)
                self.backward(x,y,y_pred)
                number_points_seen+=1
                



            #update if the number of points seen==batch size, or if data ends
            if number_points_seen%batch_size==0 or number_points_seen==np.shape(X)[1]:
                for i in range(len(self.layers)):
                    layer=self.layers[i]
                    u_W[i]=beta*u_W[i]+layer.d_W
                    u_b[i]=beta*u_b[i]+layer.d_b
                    layer.W=layer.W-eta*u_W[i]
                    layer.b=layer.b-eta*u_b[i]
                self.reset() #reset grads before new update
                


    def rmsprop(self,X,Y,eta=1,beta=0.9,batch_size=100,max_iters=1000):
        ''''''
        v_W=[np.zeros(np.shape(layer.d_W)) for layer in self.layers]
        v_b=[np.zeros(np.shape(layer.d_b)) for layer in self.layers]
        t=0
        epsilon=1e-10



        for t in tqdm(range(max_iters)):
            number_points_seen=0
            for i in range(np.shape(X)[1]):
                x=X[:,[i]]
                y=Y[:,[i]]
                y_pred=self.forward(x)
                self.backward(x,y,y_pred)
                number_points_seen+=1
                


    

            #update if the number of points seen==batch size, or if data ends
            if number_points_seen%batch_size==0 or number_points_seen==np.shape(X)[1]:
                for i in range(len(self.layers)):
                    layer=self.layers[i]
                    v_W[i]=beta*v_W[i]+(1-beta)*layer.d_W**2
                    v_b[i]=beta*v_b[i]+(1-beta)*layer.d_b**2
                    layer.W=layer.W-(eta/np.sqrt(v_W[i]+epsilon))*layer.d_W
                    layer.b=layer.b-(eta/np.sqrt(v_b[i]+epsilon))*layer.d_b
                self.reset() #reset grads before new epoch
                


            
    def adam(self,X,Y,eta=1,beta1=0.9, beta2=0.999, batch_size=100,max_iters=1000):
        m_W=[np.zeros(np.shape(layer.d_W)) for layer in self.layers]
        v_W=[np.zeros(np.shape(layer.d_W)) for layer in self.layers]
        m_b=[np.zeros(np.shape(layer.d_b)) for layer in self.layers]
        v_b=[np.zeros(np.shape(layer.d_b)) for layer in self.layers]
        t=0
        epsilon=1e-10



        for t in tqdm(range(max_iters)):
            number_points_seen=0
            for i in range(np.shape(X)[1]):
                x=X[:,[i]]
                y=Y[:,[i]]
                y_pred=self.forward(x)
                self.backward(x,y,y_pred)
                number_points_seen+=1
                


    

            #update if the number of points seen==batch size, or if data ends
            if number_points_seen%batch_size==0 or number_points_seen==np.shape(X)[1]:
                for i in range(len(self.layers)):
                    layer=self.layers[i]
                    #updating momentum, velocity
                    m_W[i]=beta1*m_W[i]+(1-beta1)*layer.d_W
                    m_b[i]=beta1*m_b[i]+(1-beta1)*layer.d_b
                    
                    v_W[i]=beta2*v_W[i]+(1-beta2)*layer.d_W**2
                    v_b[i]=beta2*v_b[i]+(1-beta2)*layer.d_b**2
                    
                    m_W_hat=m_W[i]/(1-np.power(beta1,t+1))
                    m_b_hat=m_b[i]/(1-np.power(beta1,t+1))
                    v_W_hat=v_W[i]/(1-np.power(beta2,t+1))
                    v_b_hat=v_b[i]/(1-np.power(beta2,t+1))
                    
                    
                    
                    layer.W=layer.W-(eta*m_W_hat)/(np.sqrt(v_W_hat)+epsilon)
                    layer.b=layer.b-(eta*m_b_hat)/(np.sqrt(v_b_hat)+epsilon)
                self.reset() #reset grads before new epoch
    
    def NAG(self,X,Y,eta=1,beta=0.9,batch_size=100,max_iters=1000):
        ''''''
        m_W=[np.zeros(np.shape(layer.d_W)) for layer in self.layers]
        m_b=[np.zeros(np.shape(layer.d_b)) for layer in self.layers]

        



        for t in tqdm(range(max_iters)):
            number_points_seen=0
            for i in range(np.shape(X)[1]):
                x=X[:,[i]]
                y=Y[:,[i]]
                y_pred=self.forward(x)
                self.backward(x,y,y_pred)
                number_points_seen+=1
                



            #update if the number of points seen==batch size, or if data ends
            if number_points_seen%batch_size==0 or number_points_seen==np.shape(X)[1]:
                for i in range(len(self.layers)):
                    layer=self.layers[i]
                    m_W[i]=beta*m_W[i]+eta*layer.d_W
                    m_b[i]=beta*m_b[i]+eta*layer.d_b

                    
                    layer.W=layer.W-(beta*m_W[i]+eta*layer.d_W[i])
                    layer.b=layer.b-(beta*m_b[i]+eta*layer.d_b[i])
                self.reset() #reset grads before new epoch
                
                
    
    def NAdam(self,X,Y,eta=1,beta1=0.9, beta2=0.999, batch_size=100,max_iters=1000):
        m_W=[np.zeros(np.shape(layer.d_W)) for layer in self.layers]
        v_W=[np.zeros(np.shape(layer.d_W)) for layer in self.layers]
        m_b=[np.zeros(np.shape(layer.d_b)) for layer in self.layers]
        v_b=[np.zeros(np.shape(layer.d_b)) for layer in self.layers]
        t=0
        epsilon=1e-10



        for t in tqdm(range(max_iters)):
            number_points_seen=0
            for i in range(np.shape(X)[1]):
                x=X[:,[i]]
                y=Y[:,[i]]
                y_pred=self.forward(x)
                self.backward(x,y,y_pred)
                number_points_seen+=1
                


    

            #update if the number of points seen==batch size, or if data ends
            if number_points_seen%batch_size==0 or number_points_seen==np.shape(X)[1]:
                for i in range(len(self.layers)):
                    layer=self.layers[i]
                    #updating momentum, velocity
                    m_W[i]=beta1*m_W[i]+(1-beta1)*layer.d_W
                    m_b[i]=beta1*m_b[i]+(1-beta1)*layer.d_b
                    
                    v_W[i]=beta2*v_W[i]+(1-beta2)*layer.d_W**2
                    v_b[i]=beta2*v_b[i]+(1-beta2)*layer.d_b**2
                    
                    m_W_hat=m_W[i]/(1-np.power(beta1,t+1))
                    m_b_hat=m_b[i]/(1-np.power(beta1,t+1))
                    v_W_hat=v_W[i]/(1-np.power(beta2,t+1))
                    v_b_hat=v_b[i]/(1-np.power(beta2,t+1))
                    
                    
                    
                    layer.W=layer.W-(eta/(np.sqrt(v_W_hat)+epsilon))*\
                    (beta1*m_W_hat+((1-beta1)/(1-np.power(beta1,t+1)))*layer.d_W)
                    layer.b=layer.b-(eta/(np.sqrt(v_b_hat)+epsilon))*\
                    (beta1*m_b_hat+((1-beta1)/(1-np.power(beta1,t+1)))*layer.d_b)
                    
                self.reset() #reset grads before new epoch
            

                
        
            



        

        
    

In [24]:
# test_NN=optimizers(784,10,[32,32,32],['sigmoid','sigmoid','sigmoid'])

In [25]:
# # test_NN.stochastic_gradient_descent(X,Y)
# # test_NN.Momentum_based(X,Y)
# # test_NN.batch_gradient_descent(X,Y,batch_size=3,max_iters=10000)
# # test_NN.rmsprop(X,Y)
# # test_NN.adam(X,Y,eta=0.001,batch_size=2,max_iters=10000)
# test_NN.stochastic_gradient_descent(Xtrain,ytrain,eta=0.001,max_iters=10)
# # test_NN.adam(Xtrain,ytrain,eta=0.001,batch_size=64,max_iters=10)
# # test_NN.NAdam(Xtrain,ytrain,eta=0.001,batch_size=64,max_iters=10)




In [26]:
# ypred0=test_NN.forward(Xtrain[:,[0]])
# ypred1=test_NN.forward(Xtrain[:,[1]])
# ypred2=test_NN.forward(Xtrain[:,[2]])
# ypred=np.hstack((ypred0,ypred1,ypred2))

In [27]:
# Y=np.hstack((ytrain[:,[0]],ytrain[:,[1]],ytrain[:,[2]]))

In [28]:
#keep small laerning rate, batch size<shape(X)

In [29]:
a=np.transpose([[1,2,-3,4],[4,-5,6,7],[2,3,4,-5]])

In [30]:
b=np.transpose([[0,0,1,0],[0,1,0,0],[0,0,0,1]])

In [31]:
test_NN=optimizers(4,4,[3,4,3],['sigmoid','sigmoid','sigmoid'])
test_NN.stochastic_gradient_descent(a,b,eta=0.001,max_iters=100000)
ypred0=test_NN.forward(a[:,[0]])
ypred1=test_NN.forward(a[:,[1]])
ypred2=test_NN.forward(a[:,[2]])
ypred=np.hstack((ypred0,ypred1,ypred2))
print('AE:-',np.sum(np.abs(ypred-b)))
print(ypred,'\n',b)

100%|█████████████████████████████████████████████████████████████████████████| 100000/100000 [00:21<00:00, 4705.75it/s]

AE:- 4.00195210129486
[[0.00097594 0.00097611 0.00097603]
 [0.33300268 0.33300267 0.33300268]
 [0.33275256 0.33275259 0.33275258]
 [0.33326881 0.33326864 0.33326872]] 
 [[0 0 0]
 [0 1 0]
 [1 0 0]
 [0 0 1]]


In [32]:
test_NN=optimizers(4,4,[3,4,3],['sigmoid','sigmoid','sigmoid'])
test_NN.batch_gradient_descent(a,b,eta=0.001,batch_size=2,max_iters=100000)
ypred0=test_NN.forward(a[:,[0]])
ypred1=test_NN.forward(a[:,[1]])
ypred2=test_NN.forward(a[:,[2]])
ypred=np.hstack((ypred0,ypred1,ypred2))
np.sum(np.abs(ypred-b))

print('AE:-',np.sum(np.abs(ypred-b)))
print(ypred,'\n',b)

 20%|███████████████▏                                                          | 20479/100000 [00:04<00:16, 4940.23it/s]


KeyboardInterrupt: 

In [ ]:
test_NN=optimizers(4,4,[3,4,3],['sigmoid','sigmoid','sigmoid'])
test_NN.Momentum_based(a,b,eta=0.001,batch_size=2,max_iters=100000)
ypred0=test_NN.forward(a[:,[0]])
ypred1=test_NN.forward(a[:,[1]])
ypred2=test_NN.forward(a[:,[2]])
ypred=np.hstack((ypred0,ypred1,ypred2))
np.sum(np.abs(ypred-b))

print('AE:-',np.sum(np.abs(ypred-b)))
print(ypred,'\n',b)

In [ ]:
test_NN=optimizers(4,4,[3,4,3],['sigmoid','sigmoid','sigmoid'])
test_NN.rmsprop(a,b,eta=0.001,batch_size=2,max_iters=100000)
ypred0=test_NN.forward(a[:,[0]])
ypred1=test_NN.forward(a[:,[1]])
ypred2=test_NN.forward(a[:,[2]])
ypred=np.hstack((ypred0,ypred1,ypred2))
np.sum(np.abs(ypred-b))

print('AE:-',np.sum(np.abs(ypred-b)))
print(ypred,'\n',b)

In [ ]:
test_NN=optimizers(4,4,[3,4,3],['sigmoid','sigmoid','sigmoid'])
test_NN.adam(a,b,eta=0.001,batch_size=2,max_iters=100000)
ypred0=test_NN.forward(a[:,[0]])
ypred1=test_NN.forward(a[:,[1]])
ypred2=test_NN.forward(a[:,[2]])
ypred=np.hstack((ypred0,ypred1,ypred2))
np.sum(np.abs(ypred-b))

print('AE:-',np.sum(np.abs(ypred-b)))
print(ypred,'\n',b)

In [ ]:
test_NN=optimizers(4,4,[3,4,3],['sigmoid','sigmoid','sigmoid'])
test_NN.NAG(a,b,eta=0.001,batch_size=2,max_iters=100000)
ypred0=test_NN.forward(a[:,[0]])
ypred1=test_NN.forward(a[:,[1]])
ypred2=test_NN.forward(a[:,[2]])
ypred=np.hstack((ypred0,ypred1,ypred2))
np.sum(np.abs(ypred-b))

print('AE:-',np.sum(np.abs(ypred-b)))
print(ypred,'\n',b)

In [ ]:
test_NN=optimizers(4,4,[3,4,3],['sigmoid','sigmoid','sigmoid'])
test_NN.NAdam(a,b,eta=0.001,batch_size=2,max_iters=100000)
ypred0=test_NN.forward(a[:,[0]])
ypred1=test_NN.forward(a[:,[1]])
ypred2=test_NN.forward(a[:,[2]])
ypred=np.hstack((ypred0,ypred1,ypred2))
np.sum(np.abs(ypred-b))

print('AE:-',np.sum(np.abs(ypred-b)))
print(ypred,'\n',b)